### ISSUE TITLE
[Feature suggestion]: Add button for Shorts

### ISSUE THREAD

**Issue by etherealxx** [huhuang03/ytb_dni#4]
Absolutely amazing and time saving extension, thank you for making this✨

Btw could you add support for youtube shorts too? If possible of course.

And also Youtube post too if also possible.

**Comment by huhuang03** [comment]
Add for shorts means the shorts on ytb home page OR on the https://www.youtube.com/shorts/some_short_id page?

**Comment by etherealxx** [comment]
Yes the shorts part is this part of the youtube homepage (https://www.youtube.com)

![image](https://github.com/huhuang03/ytb_dni/assets/64251396/a8776837-2ff1-4a22-92dc-9b8142f8f08a)

And the Youtube post is this part of the youtube homepage

![image](https://github.com/huhuang03/ytb_dni/assets/64251396/05b96361-ad98-4a1b-94c8-989bad2dad60)

**Comment by huhuang03** [comment]
The extesnion is updated to 0.1.1 in chrome extension store. The shorts should be ok.

But I never see any posts in my youtube home page. So I'm not able to add for posts.
