### ISSUE TITLE
[Feature Suggestion] Button on side recommendation when watching a video

### ISSUE THREAD

**Issue by etherealxx** [huhuang03/ytb_dni#5]
Been using the extension for months now. Amazing for controlling youtube recommendation algorithm.

I do notices that it only works on the youtube home page, and it would be nice if it's also added here.
![image](https://github.com/huhuang03/ytb_dni/assets/64251396/c5504965-0f54-4b80-bfb6-f6bac108ec28)

**Comment by huhuang03** [comment]
Look's there no space to put the `not interested` button....

<img width="344" alt="image" src="https://github.com/huhuang03/ytb_dni/assets/4716706/080b77a8-6ad9-44b7-adde-6a8fe7c9ebb3">

**Comment by etherealxx** [comment]
i think it's not the My Mix/Playlist part, but just the recommendation on the right part when you watch a random normal youtube video
and in terms of space, there are plenty
![image](https://github.com/huhuang03/ytb_dni/assets/64251396/0aeb3b80-9d9d-47b6-bcd4-7e5a4b539253)

**Comment by huhuang03** [comment]
Thand you for your suggestion,  I have already publish a new version `0.1.4` for review.

**Comment by etherealxx** [comment]
![image](https://github.com/huhuang03/ytb_dni/assets/64251396/e93677e5-5290-4f98-badc-4867e6f2024c)

Works perfectly! Thanks for taking time implementing this✨
Have a great day
