### ISSUE TITLE
[Feature Suggestion] Option to "Tell Us Why" -> "I don't like the video" with one click

### ISSUE THREAD

**Issue by klesun** [huhuang03/ytb_dni#7]
Hi. Thank you very much for this great extension.

I'm not sure if it has any real effect, but I usually follow the "Not Interested" click with "Tell Us Why" -> "I don't like the video" to make it extra clear to youtube algorithms that I'm really really really not interested in such kind of videos.

So my personal procedure of not-interesting a video before this extension consisted of 5 clicks (triple-dot button, "Not Interested", "Tell Us Why", "I don't like the video", "Submit").

This extension currently reduces the number of clicks I have to do to 4 (which is great!), but it would be really neat if this number could be reduced further.

Maybe something like a setting in the extension to automatically send the "Tell Us Why" -> "I don't like the video" commands when you are not-interesting the video with the extension's button, or maybe some follow-up button alongside the "Tell Us Why" button to "I don't like the video" in one click.

Just dropping this idea in case you'll find it a logical continuation of this extension's development.

**Comment by huhuang03** [comment]
Got it, thank you, I will try.

**Comment by huhuang03** [comment]
Already published as version `0.1.5`

**Comment by klesun** [comment]
Wow, thank you so much!
It appears to be working on my side ^_^
Wish you all the besties!
